inherit_from: "configs/rgbd/tum/base_config.yaml"

Dataset:
  dataset_path: "/home/aeuser/MonoRTGS_ONX/datasets/rgbd_dataset_freiburg1_desk"
  Calibration:
    fx: 517.306408
    fy: 516.469215
    cx: 318.643040
    cy: 255.313989
    k1: 0.262383
    k2: -0.953104
    p1: -0.005358
    p2: 0.002628
    k3: 1.163314
    distorted: True
    width: 640
    height: 480
    depth_scale: 5000.0
    a: 180.6
    b: 10.29
    c: 12.6
    d: 90.3