inherit_from: "configs/rgbd/tum/base_config.yaml"

Dataset:
  dataset_path: "/home/aeuser/MonoRTGS_ONX/datasets/rgbd_dataset_freiburg3_long_office_household"
  Calibration:
    fx: 535.4
    fy: 539.2
    cx: 320.1
    cy: 247.6
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    distorted: False
    width: 640
    height: 480
    depth_scale: 5000.0
    a: 180.32
    b: 9.73
    c: 11.9
    d: 93.1
